# Generated by Django 2.0.6 on 2018-06-23 22:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Distributor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zipcode', models.CharField(max_length=6)),
                ('city', models.CharField(max_length=30)),
                ('phone', models.CharField(max_length=10)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, unique=True, verbose_name='User')),
            ],
        ),
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('phone', models.CharField(max_length=10)),
                ('timeleft', models.DateTimeField()),
                ('zipcode', models.CharField(max_length=6)),
                ('city', models.CharField(max_length=30)),
                ('price', models.IntegerField(default=50)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('choose', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mainApp.Distributor')),
            ],
        ),
    ]
