# Generated by Django 2.0.6 on 2018-06-23 22:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lead',
            name='timeleft',
        ),
    ]
