# Generated by Django 2.0.6 on 2018-06-23 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lead',
            name='near',
        ),
        migrations.AddField(
            model_name='lead',
            name='price',
            field=models.IntegerField(default=50),
        ),
    ]
