# Generated by Django 2.0.6 on 2018-06-23 22:18

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0002_remove_lead_timeleft'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='timeleft',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
