# Generated by Django 2.0.6 on 2018-06-24 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0004_auto_20180624_0638'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='time',
            field=models.IntegerField(default=50),
        ),
    ]
