# Generated by Django 2.0.6 on 2018-06-24 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0005_lead_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='address',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='lead',
            name='description',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='lead',
            name='city',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='lead',
            name='name',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='lead',
            name='price',
            field=models.IntegerField(blank=True, default=50),
        ),
        migrations.AlterField(
            model_name='lead',
            name='timeleft',
            field=models.DateTimeField(blank=True),
        ),
        migrations.AlterField(
            model_name='lead',
            name='zipcode',
            field=models.CharField(blank=True, max_length=6),
        ),
    ]
